/**
 * Korean display names for commonly traded US stocks and ETFs.
 * Used when the app is in Korean mode.
 */
export const KOREAN_NAMES: Record<string, string> = {
  // Big Tech
  AAPL: '애플',
  MSFT: '마이크로소프트',
  GOOGL: '알파벳 A',
  GOOG: '알파벳 C',
  AMZN: '아마존',
  META: '메타',
  NVDA: '엔비디아',
  TSLA: '테슬라',
  ORCL: '오라클',
  IBM: 'IBM',
  INTC: '인텔',
  AMD: 'AMD',
  QCOM: '퀄컴',
  TXN: '텍사스 인스트루먼트',
  AMAT: '어플라이드 머티리얼즈',
  KLAC: 'KLA',
  LRCX: '램 리서치',
  MU: '마이크론',
  MRVL: '마벨 테크놀로지',
  AVGO: '브로드컴',
  ARM: 'ARM 홀딩스',
  SMCI: '슈퍼마이크로',

  // Cloud / SaaS
  CRM: '세일즈포스',
  NOW: '서비스나우',
  SNOW: '스노우플레이크',
  PANW: '팔로알토 네트웍스',
  CRWD: '크라우드스트라이크',
  NET: '클라우드플레어',
  DDOG: '데이터독',
  MDB: '몽고DB',
  OKTA: '옥타',
  ZS: '지스케일러',
  HUBS: '허브스팟',
  WDAY: '워크데이',
  ADBE: '어도비',
  INTU: '인튜이트',
  FTNT: '포티넷',

  // Consumer / Media
  NFLX: '넷플릭스',
  DIS: '디즈니',
  SPOT: '스포티파이',
  ROKU: '로쿠',
  SNAP: '스냅',
  PINS: '핀터레스트',
  RBLX: '로블록스',
  ABNB: '에어비앤비',
  DASH: '도어대시',
  UBER: '우버',
  LYFT: '리프트',
  SHOP: '쇼피파이',
  ETSY: '엣시',
  EBAY: '이베이',

  // Finance
  JPM: 'JP모건',
  BAC: '뱅크오브아메리카',
  WFC: '웰스파고',
  C: '시티그룹',
  GS: '골드만삭스',
  MS: '모건스탠리',
  AXP: '아메리칸 익스프레스',
  V: '비자',
  MA: '마스터카드',
  PYPL: '페이팔',
  SQ: '블록',
  COIN: '코인베이스',
  HOOD: '로빈후드',
  SOFI: '소파이',
  'BRK-B': '버크셔 해서웨이 B',
  'BRK-A': '버크셔 해서웨이 A',

  // EV / Auto
  RIVN: '리비안',
  LCID: '루시드',
  F: '포드',
  GM: '제너럴모터스',
  TM: '도요타',
  STLA: '스텔란티스',

  // Healthcare / Pharma
  PFE: '화이자',
  MRNA: '모더나',
  JNJ: '존슨앤존슨',
  MRK: '머크',
  ABBV: '애브비',
  LLY: '일라이 릴리',
  UNH: '유나이티드헬스',
  CVS: 'CVS 헬스',
  BMY: '브리스톨마이어스',
  GILD: '길리어드',
  REGN: '리제네론',
  BIIB: '바이오젠',
  ILMN: '일루미나',

  // Energy
  XOM: '엑슨모빌',
  CVX: '셰브론',
  COP: '코노코필립스',
  OXY: '옥시덴탈',
  SLB: 'SLB',

  // Retail / Consumer Staples
  WMT: '월마트',
  TGT: '타겟',
  COST: '코스트코',
  HD: '홈디포',
  LOW: '로우스',
  NKE: '나이키',
  SBUX: '스타벅스',
  MCD: '맥도날드',
  KO: '코카콜라',
  PEP: '펩시코',
  PG: 'P&G',

  // Telecom
  T: 'AT&T',
  VZ: '버라이즌',
  TMUS: 'T-모바일',

  // Aerospace / Defense
  BA: '보잉',
  LMT: '록히드마틴',
  RTX: '레이시온',
  NOC: '노스럽그러먼',
  GE: 'GE 에어로스페이스',

  // Meme / Volatile
  GME: '게임스탑',
  AMC: 'AMC 엔터테인먼트',
  BBBY: '베드배스앤비욘드',
  BYND: '비욘드미트',
  PTON: '펠로톤',

  // Popular ETFs
  SPY: 'SPDR S&P 500 ETF',
  QQQ: '인베스코 QQQ',
  IWM: '아이셰어즈 러셀2000',
  DIA: 'SPDR 다우존스 ETF',
  VTI: '뱅가드 전체시장 ETF',
  TQQQ: '프로쉐어즈 울트라프로 QQQ',
  SQQQ: '프로쉐어즈 울트라프로 숏 QQQ',
  SOXL: '디렉시온 반도체 레버리지',
  SOXS: '디렉시온 반도체 숏',
  UVXY: '프로쉐어즈 울트라 VIX',
  LABU: '디렉시온 바이오텍 레버리지',
  LABD: '디렉시온 바이오텍 숏',
  TNA: '디렉시온 소형주 레버리지',
  TZA: '디렉시온 소형주 숏',
  UPRO: '프로쉐어즈 울트라프로 S&P500',
  SPXS: '디렉시온 S&P500 숏',
  FAS: '디렉시온 금융 레버리지',
  FAZ: '디렉시온 금융 숏',
  GLD: 'SPDR 골드 ETF',
  SLV: '아이셰어즈 실버 ETF',
  USO: '미국 오일 펀드',

  // China ADR
  BABA: '알리바바',
  JD: 'JD닷컴',
  PDD: '핀둬둬',
  BIDU: '바이두',
  NIO: '니오',
  XPEV: '샤오펑',
  LI: '리오토',
};
